apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-serviceaccount
  namespace: ingress-space

  # Sau đó phải cấu hình Role + RoleBinding cho service-account này
  #             Cluster Role + Cluster RoleBinding