apiVersion: v1
kind: Pod
metadata:
  name: bee
  labels:
    type: Front-end
spec:
   containers:
      - name: nginx
        image: nginx
   tolerations:
     - key: spray
       operator: Equal
       value: mortein
       effect: NoSchedule