# Sẽ khác ở EKS
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
  - system:authenticated
  usages:
  - client auth
  signerName: kubernetes.io/kube-apiserver-client
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQWxmbXVHUmswQWRBUlpJQm56UjNPcHV1NWNlV3N4b2hMTlROdERqY055WUlsCm5rUHlyNko0dFlFeFZPUzVlUndyS25ibVFZcWxMbWJjdW1vUGk0SVpEY2JXRTJ4c2tSV21Mc2FvK290MzdLNGIKc0QwZTEwNjUyOXZaQU9jd1htdnBVNlBGY0k1R0I4NGdBUnJwcnVxeWVBeWJxamNOdGdPdkhRNE15MWJoNnk0TApJa1NJaFF3Rkh4OHdWSnNtS2wycTZhSHA5djJZOFpkQkZ2RlQ3a1dyQ2ZGeE1XTG5mQWdPbHZIMDI0cGlYMURwCnd2c1JCdHYwUFlmQUZpV056NlhkZHBMaEswN0RIVnM3SFBwa0V2Sm1zOFh5M0Z2UTFEcHNYejExMmFXc20xL0sKSVdaVXBlVmR3dEUxT2U5RnVGNDU4SmxWaVZMV2NaQy9VWHlqSXRTU1V3SURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBQzJQbkJsSjNISWlvMlg0QTJjem8zT2F6a25sMUlLRm9lZURHNUNPSW1Ia0IzYnpmVE9LCjFVaC94RGF1Z0pKVVNIY0FhanBoeDVZQ0NTaGFvd2tUQkhjNC9uSG0wbm9XVTNMOUZaOTlNZFJaQW9jRkQ5MlgKTEgwRUFqQStnNXMyZmdaZG1OZldEY05rb0RmZXkyN3ZsbDlZaEJERllHNzd5Q3BXNDQreGNiOWpJMlNjeWhmRwpWemhCd3d6ZVAweW9nMzFFUndvZHBqUHlZWFptTDhYWnNhM2lWaFp3SmJkY3l3bWlrdXI3VCtXeHdKMlVHaTdCCkNsR0JVcU8rWVdJRm9mdHl5ejcrYmlCZnNiNzVNcVR1RTRjTVI0T25LRWs4R2ZPcVRIaGU2TmFveVpNYTZZTjQKVDBtVFo0Z2g0UGV2QUJPT0Q2Q3kvZ1FYaWY4QVNETHlwVVU9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=