apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
rules:
- apiGroups: [""]   # Để trống thì hiểu là /api/v1
  resources: ["pods"]
  verbs: ["list", "get", "create", "update"]
  namespaces: ["prod","dev"]
- apiGroups: [""]
  resources: ["ConfigMap"]
  verbs: ["create"]
# namespaces: #Ko có nghĩa là default