apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: elastic-stack
  labels:
    name: app
spec:
  containers:
  - name: app
    image: kodekloud/event-simulator
    volumeMounts:
    - mountPath: /log                           # Đường dẫn bên trong container
      name: log-volume                          # Tên volume bên ngoài container mà nó sẽ mount

  - name: sidecar
    image: kodekloud/filebeat-configured
    volumeMounts:
    - mountPath: /var/log/event-simulator/      # Đường dẫn bên trong container
      name: log-volume                          # Tên volume bên ngoài container mà nó sẽ mount

  volumes:
  - name: log-volume                            # Tên volume bên ngoài container mà nó sẽ mount
    hostPath:
      # directory location on host
      path: /var/log/webapp                     # đường dẫn ở node
      # this field is optional
      type: DirectoryOrCreate